image: php:8.1-cli

pipelines:
  branches:
    dev:
      - step:
          name: Deploy to EC2
          script:
            - apt-get update
            - apt-get install -y openssh-client sudo
            - ssh-keyscan -H 3.12.116.180 >> ~/.ssh/known_hosts
            - ssh root@3.12.116.180 "cd /var/www/html/eventium365-backend && ./deploy.sh"